"""Ego-graph expansion helpers for WorldRecall.expand (strict leaf)."""

from __future__ import annotations

import json
from datetime import datetime
from typing import Any

from .recall_common import _objects_by_id, _rows, _usage_evidence_counts
from .store import WorldStore

_EGO_NEIGHBOR_CAP = 5
_EGO_STATUS_CAP = 3
_EGO_TIMELINE_CAP = 5
_EGO_EDGE_POOL = 120
_EGO_EVENT_EDGE_CAP = 12


class _EgoView:
    __slots__ = (
        "neighbors",
        "statuses",
        "timeline",
        "event_edges",
        "participated_events",
        "omitted_counts",
        "sort_basis",
        "event_next_cursor",
        "truncated",
    )

    def __init__(
        self,
        *,
        neighbors: list[dict[str, Any]],
        statuses: list[dict[str, Any]],
        timeline: list[dict[str, Any]],
        event_edges: list[dict[str, Any]],
        participated_events: list[dict[str, Any]],
        omitted_counts: dict[str, int],
        sort_basis: str,
        event_next_cursor: str | None,
        truncated: bool,
    ) -> None:
        self.neighbors = neighbors
        self.statuses = statuses
        self.timeline = timeline
        self.event_edges = event_edges
        self.participated_events = participated_events
        self.omitted_counts = omitted_counts
        self.sort_basis = sort_basis
        self.event_next_cursor = event_next_cursor
        self.truncated = truncated


def _parse_event_cursor(raw: str | None) -> tuple[str, str] | None:
    """Parse a participated-events page cursor into an (event_time_start, id) pair.

    The cursor is the JSON token ``event_next_cursor`` emits (spec-shaped
    ``{"t": <event_time_start>, "id": <event_id>}``); the time must be a
    parseable ISO datetime so a garbage cursor fails loudly at the recall
    boundary (the tools facade maps the ValueError to a typed
    invalid_arguments limitation). Comparison stays string-based on the
    stored UTC ISO shape, so a cursor generated by this read round-trips
    exactly.
    """
    if raw is None:
        return None
    try:
        data = json.loads(raw)
    except (TypeError, ValueError) as error:
        raise ValueError("invalid event cursor") from error
    if not isinstance(data, dict) or not isinstance(data.get("t"), str) or not isinstance(
        data.get("id"), str
    ):
        raise ValueError("invalid event cursor")
    moment = data["t"]
    identifier = data["id"]
    if not moment or not identifier:
        raise ValueError("invalid event cursor")
    try:
        datetime.fromisoformat(moment.replace("Z", "+00:00"))
    except ValueError as error:
        raise ValueError("invalid event cursor") from error
    return moment, identifier


def _event_cursor_json(moment: str, identifier: str) -> str:
    """Render the next-page cursor token for the last returned participated event."""
    return json.dumps({"t": moment, "id": identifier})


def _expand_ego(
    store: WorldStore,
    roots: list[str],
    *,
    event_limit: int,
    before: tuple[str, str] | None,
) -> _EgoView:
    """Ego-graph slice for expand(): direct neighbors, current status, event surface.

    The ego zoom stays *direct*: only assertions whose subject or object is
    one of the requested roots contribute, so depth never widens the ego
    (the legacy depth/limit frontier still extends ``neighboring_objects``).
    Neighbor edges are object-valued assertions pointing at a distinct other
    object; self-references and edges between two roots never spawn
    neighbors. The join is written as ``LEFT JOIN objects o ON o.id =
    a.object_id`` plus ``o.id IS NOT NULL`` so the traced SQL never contains
    the retired ``object_id IS NOT NULL`` gate (audit F4). Each section is
    capped (5 neighbors / 3 status / 5 timeline / 12 event edges /
    event_limit participated events) and any over-cap truncation OR-merges
    into the bundle's ``truncated`` flag while the per-section drop counts
    land in ``omitted_counts`` (contract: cap cuts are never silent).

    Dense event relationships (task 4.2) stay event nodes plus participant
    assertions — no team<->team per-match edges are synthesized. Event
    roots expose their ``has_participant`` edges (``event_edges``, with
    role/qualifiers/evidence summaries); entity roots reverse those edges
    into the recent events they participate in (``participated_events``,
    ``event_time_start DESC, id ASC`` — a stable sort whose ties break on
    event id ascending — paged through the optional *before* cursor and the
    emitted ``event_next_cursor``). Both event sections are read from
    objects + assertions only (there is no events table; task 2.3 ruling).
    """
    if not roots:
        return _EgoView(
            neighbors=[],
            statuses=[],
            timeline=[],
            event_edges=[],
            participated_events=[],
            omitted_counts={},
            sort_basis="",
            event_next_cursor=None,
            truncated=False,
        )
    neighbor_rows: dict[str, dict[str, Any]] = {}
    neighbor_predicates: dict[str, list[str]] = {}
    neighbor_edge_ids: dict[str, list[str]] = {}
    status_rows: list[dict[str, Any]] = []
    timeline_rows: list[dict[str, Any]] = []
    seen_timeline: set[str] = set()
    neighbor_capped = False
    status_capped = False
    timeline_capped = False
    omitted_counts: dict[str, int] = {}
    event_edges: list[dict[str, Any]] = []
    participated_rows: dict[str, dict[str, Any]] = {}
    ordered: list[dict[str, Any]] = []
    event_omitted = 0
    edge_omitted = 0
    with store.read_connection() as connection:
        marks = ", ".join("?" for _ in roots)
        root_rows = _rows(
            connection.execute(
                f"SELECT id, kind, event_time_start FROM objects WHERE id IN ({marks})", roots
            ).fetchall()
        )
        root_kinds = {row["id"]: row["kind"] for row in root_rows}
        root_event_times = {row["id"]: row["event_time_start"] for row in root_rows}
        for root in roots:
            for row in _rows(
                connection.execute(
                    "SELECT a.* FROM assertions a"
                    " LEFT JOIN objects o ON o.id = a.object_id"
                    " WHERE (a.subject_id = ? OR a.object_id = ?)"
                    " AND NOT EXISTS (SELECT 1 FROM assertions s"
                    " WHERE s.supersedes_id = a.id)"
                    " AND o.id IS NOT NULL ORDER BY a.id LIMIT ?",
                    (root, root, _EGO_EDGE_POOL),
                ).fetchall()
            ):
                other = row["object_id"] if row["subject_id"] == root else row["subject_id"]
                if other is None or other in roots:
                    continue
                if other not in neighbor_rows:
                    neighbor_rows[other] = row
                    neighbor_predicates[other] = []
                    neighbor_edge_ids[other] = []
                neighbor_predicates[other].append(row["predicate"])
                neighbor_edge_ids[other].append(row["id"])
            status_batch = _rows(
                connection.execute(
                    "SELECT * FROM assertions WHERE subject_id = ? AND object_id IS NULL"
                    " AND event_time_start IS NULL"
                    " AND NOT EXISTS (SELECT 1 FROM assertions s"
                    " WHERE s.supersedes_id = assertions.id)"
                    " ORDER BY COALESCE(event_time_start, '') DESC, id DESC LIMIT ?",
                    (root, _EGO_STATUS_CAP + 1),
                ).fetchall()
            )
            if len(status_batch) > _EGO_STATUS_CAP:
                status_capped = True
            status_rows.extend(status_batch)
            timeline_batch = _rows(
                connection.execute(
                    "SELECT * FROM assertions WHERE (subject_id = ? OR object_id = ?)"
                    " AND event_time_start IS NOT NULL"
                    " AND NOT EXISTS (SELECT 1 FROM assertions s"
                    " WHERE s.supersedes_id = assertions.id)"
                    " ORDER BY COALESCE(event_time_start, '') DESC, id DESC LIMIT ?",
                    (root, root, _EGO_TIMELINE_CAP + 1),
                ).fetchall()
            )
            if len(timeline_batch) > _EGO_TIMELINE_CAP:
                timeline_capped = True
            for row in timeline_batch:
                if row["id"] in seen_timeline:
                    continue
                seen_timeline.add(row["id"])
                timeline_rows.append(row)
        # ── event sections (task 4.2) ──────────────────────────────────────
        # Event roots fan out through their has_participant edges; entity
        # roots fan in through the reverse edge into recent events. Both read
        # objects + assertions only (no events table; task 2.3 ruling) and
        # never synthesize team<->team per-match edges.
        event_root_ids = [root for root in roots if root_kinds.get(root) == "event"]
        entity_root_ids = [root for root in roots if root in root_kinds and root_kinds[root] != "event"]
        edge_total = 0
        for root in event_root_ids:
            edge_batch = _rows(
                connection.execute(
                    "SELECT * FROM assertions WHERE subject_id = ? AND predicate = ?"
                    " AND NOT EXISTS (SELECT 1 FROM assertions s"
                    " WHERE s.supersedes_id = assertions.id) ORDER BY id LIMIT ?",
                    (root, "has_participant", _EGO_EVENT_EDGE_CAP + 1),
                ).fetchall()
            )
            edge_total += int(
                connection.execute(
                    "SELECT COUNT(*) FROM assertions WHERE subject_id = ? AND predicate = ?"
                    " AND NOT EXISTS (SELECT 1 FROM assertions s"
                    " WHERE s.supersedes_id = assertions.id)",
                    (root, "has_participant"),
                ).fetchone()[0]
            )
            edge_ids = {item["id"] for item in event_edges}
            for row in edge_batch:
                # has_participant is an object edge by contract; a malformed
                # literal row would otherwise KeyError the name lookup below
                if row["id"] in edge_ids or row["object_id"] is None:
                    continue
                edge_ids.add(row["id"])
                event_edges.append(row)
        # the omission is measured on the merged aggregate: the returned page
        # is capped at _EGO_EVENT_EDGE_CAP across ALL event roots
        edge_omitted = max(0, edge_total - _EGO_EVENT_EDGE_CAP)
        if entity_root_ids:
            entity_marks = ", ".join("?" for _ in entity_root_ids)
            # continuation strictly AFTER the cursor in (event_time_start DESC,
            # id ASC) order: older time, or equal time with a larger id
            cursor_filter = (
                " AND (o.event_time_start < ? OR (o.event_time_start = ? AND o.id > ?))"
                if before is not None
                else ""
            )
            cursor_parameters: list[object] = []
            if before is not None:
                cursor_parameters.extend([before[0], before[0], before[1]])
            count_row = connection.execute(
                "SELECT COUNT(DISTINCT a.subject_id) FROM assertions a"
                " JOIN objects o ON o.id = a.subject_id"
                f" WHERE a.object_id IN ({entity_marks}) AND a.predicate = ?"
                " AND o.kind = ? AND o.event_time_start IS NOT NULL"
                " AND NOT EXISTS (SELECT 1 FROM assertions s"
                " WHERE s.supersedes_id = a.id)" + cursor_filter,
                (*entity_root_ids, "has_participant", "event", *cursor_parameters),
            ).fetchone()
            candidates = int(count_row[0])
            for root in entity_root_ids:
                parameters: list[object] = [root, "has_participant", "event"]
                parameters.extend(cursor_parameters)
                parameters.append(event_limit + 1)
                event_batch = _rows(
                    connection.execute(
                        "SELECT a.id AS assertion_id, a.subject_id AS event_id,"
                        " a.qualifiers_json, a.epistemic_role, a.confidence,"
                        " o.canonical_name AS event_name, o.event_time_start AS event_time_start"
                        " FROM assertions a JOIN objects o ON o.id = a.subject_id"
                        " WHERE a.object_id = ? AND a.predicate = ?"
                        " AND o.kind = ? AND o.event_time_start IS NOT NULL"
                        " AND NOT EXISTS (SELECT 1 FROM assertions s"
                        " WHERE s.supersedes_id = a.id)" + cursor_filter
                        + " ORDER BY o.event_time_start DESC, o.id ASC LIMIT ?",
                        parameters,
                    ).fetchall()
                )
                for row in event_batch:
                    if row["event_id"] in participated_rows:
                        continue
                    participated_rows[row["event_id"]] = row
            # batches are root-grouped; re-sort globally so the merge is
            # (event_time_start DESC, id ASC) across ALL roots, never a
            # root-grouped concatenation. Two stable passes: id ASC first,
            # then time DESC, so equal-time events keep id ASC (a single
            # reverse=True would flip both keys).
            ordered = sorted(
                participated_rows.values(), key=lambda row: row["event_id"]
            )
            ordered.sort(key=lambda row: row["event_time_start"], reverse=True)
            returned_count = min(event_limit, len(ordered))
            event_omitted = max(0, candidates - returned_count)
        timeline_object_ids = list(
            dict.fromkeys(row["object_id"] for row in timeline_rows if row["object_id"])
        )
        timeline_names = (
            {
                row["id"]: row["canonical_name"]
                for row in _objects_by_id(connection, timeline_object_ids)
            }
            if timeline_object_ids
            else {}
        )
        neighbor_names = (
            {
                row["id"]: row["canonical_name"]
                for row in _objects_by_id(connection, list(neighbor_rows))
            }
            if neighbor_rows
            else {}
        )
        edge_object_ids = list(dict.fromkeys(row["object_id"] for row in event_edges))
        edge_names = (
            {
                row["id"]: row["canonical_name"]
                for row in _objects_by_id(connection, edge_object_ids)
            }
            if edge_object_ids
            else {}
        )
        edge_evidence = _usage_evidence_counts(connection, [row["id"] for row in event_edges])
        participated_evidence = _usage_evidence_counts(
            connection, [row["assertion_id"] for row in ordered[:event_limit]]
        )
    status_by_id: dict[str, dict[str, Any]] = {}
    for row in status_rows:
        status_by_id.setdefault(row["id"], row)
    status_all = list(status_by_id.values())
    if len(status_all) > _EGO_STATUS_CAP:
        status_capped = True
    if len(neighbor_rows) > _EGO_NEIGHBOR_CAP:
        neighbor_capped = True
    if len(timeline_rows) > _EGO_TIMELINE_CAP:
        # the per-root batches are each capped locally; the merged aggregate
        # must be re-checked so an over-cap drop across roots marks truncated
        timeline_capped = True
    # the merge is root-grouped (each batch is already event-time-sorted), so
    # re-sort globally: spec §3.1 orders the timeline by event time, and a
    # naive concatenation could cut a newer event while keeping an older one
    timeline_rows.sort(key=lambda row: (row["event_time_start"], row["id"]), reverse=True)
    neighbor_omitted = max(0, len(neighbor_rows) - _EGO_NEIGHBOR_CAP)
    status_omitted = max(0, len(status_all) - _EGO_STATUS_CAP)
    timeline_omitted = max(0, len(timeline_rows) - _EGO_TIMELINE_CAP)
    for label, count in (
        ("neighbors", neighbor_omitted),
        ("statuses", status_omitted),
        ("timeline", timeline_omitted),
        ("event_edges", edge_omitted),
        ("participated_events", event_omitted),
    ):
        if count > 0:
            omitted_counts[label] = count
    neighbors = [
        {
            "id": identifier,
            "canonical_name": neighbor_names.get(identifier, ""),
            "predicates": sorted(set(neighbor_predicates[identifier])),
            "assertion_ids": neighbor_edge_ids[identifier],
        }
        for identifier in list(neighbor_rows)[:_EGO_NEIGHBOR_CAP]
    ]
    statuses = [
        {
            "id": row["id"],
            "predicate": row["predicate"],
            "literal": json.loads(row["literal_json"]) if row["literal_json"] else None,
            "event_time_start": row["event_time_start"],
        }
        for row in status_all[:_EGO_STATUS_CAP]
    ]
    timeline = [
        {
            "id": row["id"],
            "predicate": row["predicate"],
            "event_time_start": row["event_time_start"],
            "literal": json.loads(row["literal_json"]) if row["literal_json"] else None,
            "object": (
                {"id": row["object_id"], "canonical_name": timeline_names[row["object_id"]]}
                if row["object_id"]
                else None
            ),
        }
        for row in timeline_rows[:_EGO_TIMELINE_CAP]
    ]
    event_edges_rendered = [
        {
            "id": row["id"],
            "object": {"id": row["object_id"], "canonical_name": edge_names[row["object_id"]]},
            "role": str(
                (json.loads(row["qualifiers_json"]) if row["qualifiers_json"] else {}).get("role", "")
            ),
            "qualifiers": json.loads(row["qualifiers_json"]) if row["qualifiers_json"] else {},
            "event_time_start": root_event_times[row["subject_id"]],
            "epistemic_role": row["epistemic_role"],
            "confidence": row["confidence"],
            "evidence_counts": edge_evidence.get(row["id"], {}),
        }
        for row in event_edges[:_EGO_EVENT_EDGE_CAP]
    ]
    participated = [
        {
            "id": row["event_id"],
            "canonical_name": row["event_name"],
            "event_time_start": row["event_time_start"],
            "role": str(
                (json.loads(row["qualifiers_json"]) if row["qualifiers_json"] else {}).get("role", "")
            ),
            "assertion_id": row["assertion_id"],
            "qualifiers": json.loads(row["qualifiers_json"]) if row["qualifiers_json"] else {},
            "evidence_counts": participated_evidence.get(row["assertion_id"], {}),
        }
        for row in ordered[:event_limit]
    ]
    next_cursor = (
        _event_cursor_json(participated[-1]["event_time_start"], participated[-1]["id"])
        if participated and event_omitted > 0
        else None
    )
    return _EgoView(
        neighbors=neighbors,
        statuses=statuses,
        timeline=timeline,
        event_edges=event_edges_rendered,
        participated_events=participated,
        omitted_counts=omitted_counts,
        sort_basis="event_time_start DESC, id ASC" if participated else "",
        event_next_cursor=next_cursor,
        truncated=(
            neighbor_capped
            or status_capped
            or timeline_capped
            or event_omitted > 0
            or edge_omitted > 0
        ),
    )
